/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2020-03-09 03:46:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUpForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"#\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name = \"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content = \"ie-edge\">\r\n");
      out.write("<meta name = \"format-detection\" content = \"telephone-no\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/signUpForm.css\">\r\n");
      out.write("<link rel= \"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/signUpForm_tablet.css\" media=\"all and (max-width:1420px)\">\r\n");
      out.write("<link rel= \"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/signUpForm_moblie.css\" media=\"all and (max-width:760px)\">\r\n");
      out.write("<title>속닥속닥 :: 회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function goPopup(){\r\n");
      out.write("\tvar pop = window.open(\"");
      out.print( request.getContextPath() );
      out.write("/popup/jusoPopup.jsp\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("}\r\n");
      out.write("function jusoCallBack(roadFullAddr){\r\n");
      out.write("\t\t// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\t\r\n");
      out.write("\t\tdocument.member.userAddr.value = roadFullAddr;\t\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t// 공백체크\r\n");
      out.write("\tvar empJ = /\\s/g;\r\n");
      out.write("\t// 닉네임 정규식 (한글 영문소~대문자 숫자 입력만 가능)\r\n");
      out.write("\tvar nameJ = /^[가-힣a-z0-9]*$/;\r\n");
      out.write("\t//이메일 정규식\r\n");
      out.write("\tvar mailJ = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;\r\n");
      out.write("\t// 비밀번호 정규식\r\n");
      out.write("\tvar pwJ = /^[A-Za-z0-9]{4,12}$/;\r\n");
      out.write("\t// 휴대폰 번호 정규식\r\n");
      out.write("\tvar phoneJ = /^01([0|1|6|7|8|9]?)?([0-9]{3,4})?([0-9]{4})$/;\r\n");
      out.write("\t// 생일\r\n");
      out.write("\tvar birthJ = /^(19[0-9][0-9]|20\\d{2})(0[0-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])$/;\r\n");
      out.write("\t// 주소\r\n");
      out.write("\tvar address = $('#userAddr');\r\n");
      out.write("\t\r\n");
      out.write("\talert(\"정규식 로드\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar overlap = 0;\r\n");
      out.write("\t\tvar overlap2 = 0;\r\n");
      out.write("\t\tvar address = $('#userAddr');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//닉네임 중복확인\r\n");
      out.write("\t\t$(\"#username\").blur(function() {\r\n");
      out.write("\t\t\tif($('#username').val()==''){\r\n");
      out.write("\t\t\t\t$('#name_check').text('닉네임를 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#name_check').css('color', 'red');\r\n");
      out.write("\t\t\t} else if(nameJ.test($('#username').val())!=true){\r\n");
      out.write("\t\t\t\t$('#name_check').text('한글, 영문 소문자, 숫자만 사용 가능합니다.');\r\n");
      out.write("\t\t\t\t$('#name_check').css('color', 'red');\r\n");
      out.write("\t\t\t} else if($('#username').val()!=''){\r\n");
      out.write("\t\t\t\tvar name = $('#username').val();\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\taync : false,\r\n");
      out.write("\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tdata : {name : name},\r\n");
      out.write("\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/confirmName',\r\n");
      out.write("\t\t\t\t\t error:function(err){\r\n");
      out.write("\t\t\t\t\t\t  alert(\"서비스가 원활하지 못합니다.  잠시후 다시 시도해주세요\");\r\n");
      out.write("\t                      console.log(err.status+\" \"+ err.statusText);\r\n");
      out.write("\t                 },\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\toverlap = data;\r\n");
      out.write("\t\t\t\t\t\tif(data > 0){\r\n");
      out.write("\t\t\t\t\t\t$('#name_check').text('중복된 닉네임입니다.');\r\n");
      out.write("\t\t\t\t\t\t$('#name_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#usercheck\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tif(nameJ.test(name)){\r\n");
      out.write("\t\t\t\t\t$('#name_check').text('사용가능한 닉네임입니다.');\r\n");
      out.write("\t\t\t\t\t$('#name_check').css('color', 'blue');\r\n");
      out.write("\t\t\t\t\t$(\"#usercheck\").attr(\"disabled\", false); // (disabled : false == 활성화)\r\n");
      out.write("\t\t\t} else if(name == ''){\r\n");
      out.write("\t\t\t\t$('#name_check').text('닉네임를 입력해주세요.');\r\n");
      out.write("\t\t\t\t$('#name_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t$(\"#usercheck\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\t$('#name_check').text(\"닉네임은 한글, 소문자와 숫자만 가능합니다.\");\r\n");
      out.write("\t\t\t\t$('#name_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t$(\"#usercheck\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t});//ajax///\r\n");
      out.write("\t\t}//else if\r\n");
      out.write("\t\t});//blur\r\n");
      out.write("\t\t\r\n");
      out.write("///////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\t$(\"#email\").blur(function() {\r\n");
      out.write("\t\t\tif($('#email').val()==''){\r\n");
      out.write("\t\t\t\t$('#email_check').text('이메일을 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#email_check').css('color', 'red');\r\n");
      out.write("\t\t\t} else if(mailJ.test($('#email').val())!=true){\r\n");
      out.write("\t\t\t\t$('#email_check').text('이메일 형식을 지켜주세요.');\r\n");
      out.write("\t\t\t\t$('#email_check').css('color', 'red');\r\n");
      out.write("\t\t\t} else if($('#email').val()!=''){\r\n");
      out.write("\t\t\t\tvar email = $('#email').val();\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\taync : false,\r\n");
      out.write("\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tdata : {email : email},\r\n");
      out.write("\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ConfirmEmail',\r\n");
      out.write("\t\t\t\t\t error:function(err){\r\n");
      out.write("\t\t\t\t\t\t  alert(\"서비스가 원활하지 못합니다.  잠시후 다시 시도해주세요\");\r\n");
      out.write("\t                      console.log(err.status+\" \"+ err.statusText);\r\n");
      out.write("\t                 },\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\toverlap2 = data;\r\n");
      out.write("\t\t\t\t\t\tif(data > 0){\r\n");
      out.write("\t\t\t\t\t\t$('#email_check').text('중복된 이메일입니다.');\r\n");
      out.write("\t\t\t\t\t\t$('#email_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#usercheck\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tif(mailJ.test(email)){\r\n");
      out.write("\t\t\t\t\t$('#email_check').text('사용가능한 이메일입니다.');\r\n");
      out.write("\t\t\t\t\t$('#email_check').css('color', 'blue');\r\n");
      out.write("\t\t\t\t\t$(\"#usercheck\").attr(\"disabled\", false); // (disabled : false == 활성화)\r\n");
      out.write("\t\t\t} else if(email == ''){\r\n");
      out.write("\t\t\t\t$('#email_check').text('이메일을 입력해주세요.');\r\n");
      out.write("\t\t\t\t$('#email_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t$(\"#usercheck\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\t$('#email_check').text(\"이메일형식을 지켜주세요.\");\r\n");
      out.write("\t\t\t\t$('#email_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t$(\"#usercheck\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t});//ajax///\r\n");
      out.write("\t\t}//else if\r\n");
      out.write("\t\t});//blur\r\n");
      out.write("\t\t\r\n");
      out.write("///////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\t\t$('form').on('submit', function() {\r\n");
      out.write("\t\t\t\tvar inval_Arr = new Array(7).fill(false);\r\n");
      out.write("\t\t\t\talert(\"정규식체크2\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//성별 확인\r\n");
      out.write("\t\t\t\tif(member.gender[0].checked==false&&member.gender[1].checked==false){\r\n");
      out.write("\t\t\t\t\tinval_Arr[0] = false;\r\n");
      out.write("\t\t\t\t\talert('성별을 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\tinval_Arr[0] = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 닉네임 정규식 및 확인\r\n");
      out.write("\t\t\t\tif (nameJ.test($('#username').val()) && $('#username').val().length > 0 && overlap < 0) {\r\n");
      out.write("\t\t\t\t\tinval_Arr[1] = true;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tinval_Arr[1] = false;\r\n");
      out.write("\t\t\t\t\talert('닉네임을 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 이메일 정규식\r\n");
      out.write("\t\t\t\tif (mailJ.test($('#email').val()) && overlap2 < 0) {\r\n");
      out.write("\t\t\t\t\tconsole.log(mailJ.test($('#email').val()));\r\n");
      out.write("\t\t\t\t\tinval_Arr[2] = true;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tinval_Arr[2] = false;\r\n");
      out.write("\t\t\t\t\talert('이메일을 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 비밀번호가 같은 경우 && 비밀번호 정규식\r\n");
      out.write("\t\t\t\tif (pwJ.test($('#password').val()) && ($('#password').val() == ($('#password2').val()))) {\r\n");
      out.write("\t\t\t\t\tinval_Arr[3] = true;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tinval_Arr[3] = false;\r\n");
      out.write("\t\t\t\t\talert('비밀번호를 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 휴대전화번호 정규식\r\n");
      out.write("\t\t\t\tif (phoneJ.test($('#phone-number').val()) && $('#phone-number').val().length > 9) {\r\n");
      out.write("\t\t\t\t\tconsole.log(phoneJ.test($('#phone-number').val()));\r\n");
      out.write("\t\t\t\t\tinval_Arr[4] = true;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tinval_Arr[4] = false;\r\n");
      out.write("\t\t\t\t\talert('휴대전화번호를 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 생년월일 정규식\r\n");
      out.write("\t\t\t\tif (birthJ.test($('#birthday').val())) {\r\n");
      out.write("\t\t\t\t\tconsole.log(birthJ + \"생일\");\r\n");
      out.write("\t\t\t\t\tinval_Arr[5] = true;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tinval_Arr[5] = false;\r\n");
      out.write("\t\t\t\t\talert('생년월일을 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 주소 입력확인\r\n");
      out.write("\t\t\t\tif(address.val() == ''){\r\n");
      out.write("\t\t\t\t\tinval_Arr[6] = false;\r\n");
      out.write("\t\t\t\t\talert('주소를 확인하세요.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else\r\n");
      out.write("\t\t\t\t\tinval_Arr[6] = true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//전체 유효성 검사\r\n");
      out.write("\t\t\t\tvar validAll = true;\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < inval_Arr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(inval_Arr[i] == false){\r\n");
      out.write("\t\t\t\t\t\tvalidAll = false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(validAll == true){ // 유효성 모두 통과\r\n");
      out.write("\t\t\t\t\t\talert('속닥속닥의 가족이 되어주셔서 감사합니다.');\r\n");
      out.write("\t\t\t\t\t\talert('관심사를 선택해주세요.');\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\talert('정보를 다시 확인하세요.');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("///////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\t\t// 패스워드 체크\r\n");
      out.write("\t\t\t$('#password').blur(function() {\r\n");
      out.write("\t\t\t\tif (pwJ.test($('#password').val())) {\r\n");
      out.write("\t\t\t\t\tconsole.log('true');\r\n");
      out.write("\t\t\t\t\t$('#pw_check').text('');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tconsole.log('false');\r\n");
      out.write("\t\t\t\t\t$('#pw_check').text('4~12자의 숫자 , 문자로만 사용 가능합니다.');\r\n");
      out.write("\t\t\t\t\t$('#pw_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 패스워드 일치 확인\r\n");
      out.write("\t\t\t$('#password2').blur(function() {\r\n");
      out.write("\t\t\t\tif ($('#password2').val() != $('#password').val()) {\r\n");
      out.write("\t\t\t\t\t$('#pw_check').text('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("\t\t\t\t\t$('#pw_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#pw_check').text('비밀번호가 일치합니다.');\r\n");
      out.write("\t\t\t\t\t$('#pw_check').css('color', 'blue');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 이메일\r\n");
      out.write("\t\t\t$(\"#email\").blur(function() {\r\n");
      out.write("\t\t\t\tif (mailJ.test($(this).val())) {\r\n");
      out.write("\t\t\t\t\t$(\"#email_check\").text('이메일을 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#email_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#email_check').text('이메일 양식을 확인해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#email_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 휴대전화\r\n");
      out.write("\t\t\t$('#phone-number').blur(function(){\r\n");
      out.write("\t\t\t\tif(phoneJ.test($(this).val()) && $(this).val().length > 9){\r\n");
      out.write("\t\t\t\t\tconsole.log(($(this).val()));\r\n");
      out.write("\t\t\t\t\t$(\"#phone_check\").text('OK');\r\n");
      out.write("\t\t\t\t\t$('#phone_check').css('color', 'blue');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#phone_check').text('휴대폰번호를 확인해주세요.');\r\n");
      out.write("\t\t\t\t$('#phone_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 생일\r\n");
      out.write("\t\t\t$('#birthday').blur(function() {\r\n");
      out.write("\t\t\t\tif(birthJ.test($(this).val()) && $(this).val().length > 7) {\r\n");
      out.write("\t\t\t\t\tconsole.log(($(this).val()));\r\n");
      out.write("\t\t\t\t\t$(\"#birth_check\").text('OK');\r\n");
      out.write("\t\t\t\t\t$('#birth_check').css('color', 'blue');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#birth_check').text('생년월일을 확인해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#birth_check').css('color', 'red');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t\t// 주소\r\n");
      out.write(" \t\t\t$('#findAddr').click(function() {\r\n");
      out.write(" \t\t\t\t$('#userAddr').focusin(function() {\r\n");
      out.write(" \t\t\t\t\tif($('#userAddr').val().length > 0) {\r\n");
      out.write(" \t\t\t\t\t\t$(\"#userAddr_check\").text('OK');\r\n");
      out.write(" \t\t\t\t\t\t$('#userAddr_check').css('color', 'blue');\r\n");
      out.write(" \t\t\t\t\t} else {\r\n");
      out.write(" \t\t\t\t\t\t$(\"#userAddr_check\").text('주소를 입력하세요.');\r\n");
      out.write(" \t\t\t\t\t\t$('#userAddr_check').css('color', 'red');\r\n");
      out.write(" \t\t\t\t\t}\r\n");
      out.write(" \t\t\t\t});\r\n");
      out.write(" \t\t\t}); \r\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("<div class = \"signup_wrap\">\r\n");
      out.write("\t<form name=\"member\" id=\"usercheck\" role = \"form\" method=\"post\" action = \"signUpPro\">\r\n");
      out.write("\t\t<h2 class = \"login_tit\">회원가입</h2>\r\n");
      out.write("\t\t\t<div class = \"info-group\">\r\n");
      out.write("\t\t\t\t<div><label for = \"gender\">성별</label></div>\r\n");
      out.write("\t\t\t\t<div style = \"font-size:16px; color: #474f55;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id= \"gender\" name=\"gender\" value=\"남\" style = \"margin-left: 10px; margin-right:10px;\">남\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id= \"gender\" name=\"gender\" value=\"여\" style = \"margin-left: 10px; margin-right:10px;\">여\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"info-group\">\r\n");
      out.write("\t\t\t\t<div><label for = \"name\">닉네임</label></div>\r\n");
      out.write("\t\t\t\t<div><input type=\"text\" name=\"username\" id=\"username\" placeholder=\"10자이하\" maxlength=\"10\" class=\"form-control\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"eheck_font\" id=\"name_check\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"info-group\">\r\n");
      out.write("\t\t\t\t<div><label for = \"email\">이메일</label></div>\r\n");
      out.write("\t\t\t\t<div><input type=\"text\" name=\"email\" id=\"email\" class=\"form-control input\" placeholder=\"예) yourEmail@gmail.com\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"eheck_font\" id=\"email_check\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"row\">\r\n");
      out.write("\t\t\t\t<div class = \"info-group col\">\r\n");
      out.write("\t\t\t\t\t<div><label for = \"password\">비밀번호</label></div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"password\" id=\"password\" name=\"password\" placeholder=\"8자 이상\" class=\"form-control form-with-form input\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"eheck_font\" id=\"pw_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class = \"info-group col\">\r\n");
      out.write("\t\t\t\t\t<div><label for = \"password2\">비밀번호 확인</label></div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"password\" id=\"password2\" name=\"password2\" placeholder=\"비밀번호 확인\" class=\"form-control form-with-form\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"eheck_font\" id=\"pw_check2\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"row\">\r\n");
      out.write("\t\t\t\t<div class= \"info-group col2\">\r\n");
      out.write("\t\t\t\t\t<div><label for = \"phoneNumber\">휴대전화번호</label></div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"text\" id=\"phone-number\" name=\"phoneNumber\" placeholder=\"예) 01012345678\" class=\"form-control input\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"eheck_font\" id=\"phone_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"row\">\r\n");
      out.write("\t\t\t\t<div class= \"info-group col2\">\r\n");
      out.write("\t\t\t\t\t<div><label for = \"birthday\">생일</label></div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"text\" id=\"birthday\" name=\"birthday\" placeholder= \"예) 19940101\" maxlength=\"8\" class=\"form-control input\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"eheck_font\" id=\"birth_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"row\">\r\n");
      out.write("\t\t\t\t<div class= \"info-group col3\">\r\n");
      out.write("\t\t\t\t\t<div><label for = \"userAddr\">내 지역</label></div>\r\n");
      out.write("\t\t\t\t\t<div><button type=\"button\" id = \"findAddr\" class=\"btn btn-warning\" onclick=\"goPopup()\">주소검색</button></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class= \"info-group col4\">\r\n");
      out.write("\t\t\t\t\t<div><label for = \"userAddr\">&nbsp;</label></div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"text\" id=\"userAddr\" name=\"userAddr\" placeholder=\"주소를 검색하세요.\" class=\"form-control\" readonly=\"true\"/></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"eheck_font\" id=\"userAddr_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class = \"rulebox mt5\">\r\n");
      out.write("\t\t\t\t<strong>첫째,</strong>\r\n");
      out.write("\t\t\t\t모든 참가자는 안전하게 행사에 참가할 권리가 있습니다.\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<strong>둘째,</strong>\r\n");
      out.write("\t\t\t\t의사소통에 있어서 예의 바르고 건설적인 태도를 늘 보여주세요.\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<strong>셋째,</strong>\r\n");
      out.write("\t\t\t\t상대방을 불편하게 한다면 그것은 이미 농담이 아닙니다.\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<strong>넷째,</strong>\r\n");
      out.write("\t\t\t\t모임 및 클래스 개설자와 참가자 모두에게 도움 될 수 있도록 서로 협업합시다.\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"회원가입\" class=\"btn\">\r\n");
      out.write("\t\t\t<!-- disabled=\"disabled\" -->\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
